# Generated by Django 5.1.3 on 2024-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff', 'active'], name='idx_is_staff_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_admin', 'active'], name='idx_is_admin_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_customer', 'country'], name='idx_is_customer_country'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='idx_date_joined_desc'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email_constraint'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_phone_constraint'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_email_phone'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'country'), name='unique_name_country'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'country'), name='unique_email_country'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone', 'country'), name='unique_phone_country'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('active', True), models.Q(('is_staff', False), ('is_admin', False)), _connector='OR'), name='check_active_for_staff_admin'),
        ),
    ]
