# Generated by Django 5.1.3 on 2024-12-01 12:24

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_user_idx_is_staff_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
