version: "3.9"

services:
  web:
    build:
      context: .
    image: asher_web_image
    container_name: asher_web
      #- .:/app  # Mount source code for development (remove in production)
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8088:80"
    networks:
      - asher_network

  db:
    image: postgres:16
    container_name: asher_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - asher_postgres_data:/var/lib/postgresql/data
    networks:
      - asher_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  asher_postgres_data:

networks:
  asher_network:
    driver: bridge
